{
 "title": "Uyuni Server with logs",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(up{job=\"$job\"} , instance)"
    }
   },
   { "name": "job", "query": "mgr-server" }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$server:9100\",  mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{instance=~\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "System Load ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "load average" }
   ],
   "targets": [
    {
     "expr": "(node_load1{instance=~\"$server:9100\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"system\"}))",
     "legendFormat": "load1"
    },
    {
     "expr": "(node_load5{instance=~\"$server:9100\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"system\"}))",
     "legendFormat": "load5"
    },
    {
     "expr": "(node_load15{instance=~\"$server:9100\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"system\"}))",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Ram",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "CPU now",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$server:9100\", mode!=\"idle\"}[5m])) / count(node_cpu_seconds_total{instance=~\"$server:9100\",  mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max by (device) (node_filesystem_size_bytes{instance=~\"$server:9100\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"}))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu{instance=~\"$server:.*\", mode=\"user\"}[5m]) or irate(node_cpu_seconds_total{instance=~\"$server:.*\", mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$server:9100\", mode=\"system\"}[5m]) or irate(node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"system\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$server:9100\", mode=\"iowait\"}[5m]) or irate(node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$server:9100\", mode!~\"user|system|iowait|guest|idle\"}[5m]) or irate(node_cpu_seconds_total{instance=~\"$server:9100\", mode!~\"user|system|iowait|guest|idle\"}[5m]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "network-tx"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "network-rx"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(1 - node_filesystem_avail_bytes{instance=~\"$server:9100\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"} / node_filesystem_size_bytes, \"shortdev\", \"$1\", \"device\", \"/dev/(.*)\")   ",
     "legendFormat": "{{shortdev}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((node_memory_MemAvailable{instance=~\"$server:9100\"} / node_memory_MemTotal) or (node_memory_MemAvailable_bytes{instance=~\"$server:9100\"} / node_memory_MemTotal_bytes))",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "disk-read"
    },
    {
     "expr": "avg(rate(node_disk_written_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "disk-write"
    }
   ]
  },
  {
   "title": "mount points",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$server:9100\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"}+0"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server:9100\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"}"
    }
   ]
  },
  { "title": "Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "JVM - Tomcat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_Threading_ThreadCount{instance=\"$server:5556\"})",
     "legendFormat": "threads"
    },
    {
     "expr": "avg(java_lang_Memory_HeapMemoryUsage_used{instance=~\"$server:5556\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Database Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "operations " }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{instance=~\"$server:9187\", datname=~\"uyuni|susemanager\"}[5m])",
     "legendFormat": "fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{instance=~\"$server:9187\", datname=~\"uyuni|susemanager\"}[5m])",
     "legendFormat": "inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{instance=~\"$server:9187\", datname=~\"uyuni|susemanager\"}[5m])",
     "legendFormat": "updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{instance=~\"$server:9187\", datname=~\"uyuni|susemanager\"}[5m])",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(pg_locks_count{instance=~\"$server:9187\" ,datname=~\"uyuni|susemanager\"})",
     "legendFormat": "locks"
    }
   ]
  },
  {
   "title": "Taskomatic Scheduler",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "tasks" }
   ],
   "targets": [
    {
     "expr": "taskomatic_scheduler_threads{instance=~\"$server:5556\"}",
     "legendFormat": "threads total"
    },
    {
     "expr": "taskomatic_scheduler_threads_active{instance=~\"$server:5556\"}",
     "legendFormat": "threads active"
    },
    {
     "expr": "increase(taskomatic_scheduler_completed_task_count{instance=~\"$server:9800\"}[2m])",
     "legendFormat": "tasks completed"
    }
   ]
  },
  {
   "title": "JVM - Taskomatic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_Threading_ThreadCount{instance=\"$server:5557\"})",
     "legendFormat": "threads "
    },
    {
     "expr": "avg(java_lang_Memory_HeapMemoryUsage_used{instance=~\"$server:5557\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Server Actions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "actions by state" }
   ],
   "targets": [
    {
     "expr": "increase(mgr_serveractions_failed{instance=~\"$server:9187\"}[2m])",
     "legendFormat": "failed"
    },
    {
     "expr": "increase(mgr_serveractions_completed{instance=~\"$server:9187\"}[2m])",
     "legendFormat": "completed"
    },
    {
     "expr": "mgr_serveractions_picked_up{instance=~\"$server:9187\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "mgr_serveractions_queued{instance=~\"$server:9187\"}",
     "legendFormat": "picked up"
    }
   ]
  },
  {
   "title": "Message Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "tasks" }
   ],
   "targets": [
    {
     "expr": "message_queue_thread_pool_threads{instance=~\"$server:80\"}",
     "legendFormat": "threads total"
    },
    {
     "expr": "message_queue_thread_pool_threads_active{instance=~\"$server:80\"}",
     "legendFormat": "threads active"
    },
    {
     "expr": "increase(message_queue_thread_pool_completed_task_count{instance=~\"$server:80\"}[2m])",
     "legendFormat": "tasks completed"
    }
   ]
  },
  {
   "title": "Opened files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(process_open_fds{instance=~'.*:555[67]'} / process_max_fds{instance=~'.*:555[67]'}, \"service\", \"taskomatic\", \"instance\",  \".*:5557\"), \"service\", \"tomcat\", \"instance\", \".*:5556\") * 100",
     "legendFormat": "% {{service}}"
    },
    {
     "expr": "label_replace(label_replace(process_open_fds{instance=~'.*:555[67]'}, \"service\", \"taskomatic\", \"instance\",  \".*:5557\"), \"service\", \"tomcat\", \"instance\", \".*:5556\")",
     "legendFormat": "Count {{service}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors in logs over time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": " sum by (job) (count_over_time({job=~\".*\"} |= `ERROR` [$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Errors logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "{job=~\".*\"} |~ `(?i) (ERROR|CRITICAL|SEVERE) `"
      }
     ]
    }
   ]
  },
  {
   "title": "Uyuni and Salt Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Salt Jobs in last 24 hrs",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "salt_jobs{fun=~\".+\"}",
       "legendFormat": "{{fun}}"
      }
     ]
    },
    {
     "title": "Salt \"state.apply\" in last 24 hrs",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "salt_jobs{fun=~\"state.apply.*\"}",
       "legendFormat": "{{fun}}"
      }
     ]
    },
    {
     "title": "Packages Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "uyuni_summary{name=\"uyuni_summary_packages_total\"}",
       "legendFormat": "total packages"
      }
     ]
    },
    {
     "title": "Channels Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
     "targets": [
      {
       "expr": "uyuni_summary{name=\"uyuni_summary_channels_total\"}",
       "legendFormat": "channels total"
      }
     ]
    },
    {
     "title": "Total Actions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "uyuni_summary{name=\"uyuni_summary_actions_total\"}",
       "legendFormat": "total actions"
      }
     ]
    },
    {
     "title": "Pending Actions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 9 },
     "targets": [
      {
       "expr": "uyuni_summary{name=\"uyuni_summary_actions_pending_total\"}",
       "legendFormat": "pending actions"
      }
     ]
    },
    {
     "title": "Actions Total in last 24h",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "uyuni_summary{name=\"uyuni_summary_actions_last_24hours_total\"}",
       "legendFormat": "actions total in last 24 hours"
      }
     ]
    },
    {
     "title": "Completed Actions in last 24h",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 9 },
     "targets": [
      {
       "expr": "uyuni_summary{name=\"uyuni_summary_actions_completed_last_24hours_total\"}",
       "legendFormat": "compelted actions in last 24 hours"
      }
     ]
    },
    {
     "title": "Failed Actions in last 24h",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 9 },
     "targets": [
      {
       "expr": "uyuni_summary{name=\"uyuni_summary_actions_failed_last_24hours_total\"}",
       "legendFormat": "failed actions in last 24 hours"
      }
     ]
    },
    {
     "title": "Salt Jobs Total in last 24h",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
     "targets": [
      {
       "expr": "sum(salt_jobs)",
       "legendFormat": "salt jobs total in last 24 hours"
      }
     ]
    }
   ]
  }
 ]
}